/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ROG
 */
public class CatatanHarian extends javax.swing.JFrame {
    ArrayList<Catatan> listCatatan; //array list yang menyimpan objek objek class Catatan
    String top[] = new String[] { "Tanggal", "Tema", "Isi" }; //judul kolom untuk tabel dengan elemen "Tanggal", "Tema", dan "Isi"
    DefaultTableModel tabel; //mendeklarasikan DefaultTableModel sebagai nama variabel tabel
    int baris, kolom; //digunakan untuk pemrosesan data tabel

    //konstruktor
    public CatatanHarian() {
        initComponents(); //untuk menginisialisasi dan menambahkan komponen-komponen GUI ke dalam frame atau panel.
        listCatatan = new ArrayList<>(); //objek array list dengan nama listCatatan yang menyimpan objek objek class Catatan 
        tabel = new DefaultTableModel(top, 0); //membuat objek DefaultTableModel dengan nama tabel dengan parameter top sebagai judul kolom dan 0 sebagai jumlah baris awal dalam tabel.
        tblDiary.setModel(tabel); //menetapkan model tabel untuk objek JTable sehingga tampilan tabel akan disesuaikan dengan model itu.
        this.setLocationRelativeTo(null); //menempatkan frame di tengah layar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelKiri = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnImpor = new javax.swing.JButton();
        btnEkspor = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        panelKanan = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDiary = new javax.swing.JTable();
        tfTanggal = new javax.swing.JTextField();
        tfTema = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taCatatanHarian = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelKiri.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/me (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(30, 30, 30)));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(23, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(14, 14, 14)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Sitka Subheading", 0, 18)); // NOI18N
        jLabel2.setText("Rahmatul Firdaus");

        btnTambah.setText("Tambah Data");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit Data");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus Data");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnImpor.setText("Import Data");
        btnImpor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImporActionPerformed(evt);
            }
        });

        btnEkspor.setText("Ekspor Data");
        btnEkspor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEksporActionPerformed(evt);
            }
        });

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(35, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel2)
                                                        .addGap(55, 55, 55))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                .createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnImpor, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnEkspor, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(17, 17, 17)))));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(48, 48, 48)
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnImpor, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEkspor, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197,
                                        Short.MAX_VALUE)
                                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)));

        javax.swing.GroupLayout panelKiriLayout = new javax.swing.GroupLayout(panelKiri);
        panelKiri.setLayout(panelKiriLayout);
        panelKiriLayout.setHorizontalGroup(
                panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelKiriLayout.createSequentialGroup()
                                .addGroup(panelKiriLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        panelKiriLayout.setVerticalGroup(
                panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelKiriLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(44, Short.MAX_VALUE)));

        panelKanan.setBackground(new java.awt.Color(203, 187, 185));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CATATAN HARIAN (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CATATAN HARIAN (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4)));
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, Short.MAX_VALUE));

        tblDiary.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null },
                        { null, null, null },
                        { null, null, null },
                        { null, null, null }
                },
                new String[] {
                        "Tanggal", "Tema", "Isi"
                }));
        tblDiary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDiaryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDiary);

        taCatatanHarian.setColumns(20);
        taCatatanHarian.setRows(5);
        jScrollPane2.setViewportView(taCatatanHarian);

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel1.setText("Tanggal");

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel6.setText("Tema");

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel7.setText("Isi Catatan Harian");

        javax.swing.GroupLayout panelKananLayout = new javax.swing.GroupLayout(panelKanan);
        panelKanan.setLayout(panelKananLayout);
        panelKananLayout.setHorizontalGroup(
                panelKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKananLayout.createSequentialGroup()
                                .addGroup(panelKananLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelKananLayout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelKananLayout.createSequentialGroup()
                                                .addGap(65, 65, 65)
                                                .addGroup(panelKananLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(panelKananLayout.createSequentialGroup()
                                                                .addComponent(jLabel7)
                                                                .addGap(43, 43, 43)
                                                                .addComponent(jScrollPane2,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 396,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(panelKananLayout.createSequentialGroup()
                                                                .addGroup(panelKananLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel1)
                                                                        .addComponent(jLabel6))
                                                                .addGap(118, 118, 118)
                                                                .addGroup(panelKananLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(tfTema,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                396,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(tfTanggal,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                396,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelKananLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)));
        panelKananLayout.setVerticalGroup(
                panelKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKananLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelKananLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(panelKananLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelKananLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelKananLayout.createSequentialGroup()
                                                .addGap(53, 53, 53)
                                                .addGroup(panelKananLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(tfTanggal, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel1))
                                                .addGap(50, 50, 50)
                                                .addGroup(panelKananLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(tfTema, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6))
                                                .addGap(50, 50, 50)
                                                .addGroup(panelKananLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jScrollPane2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 424,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(panelKiri, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelKanan, javax.swing.GroupLayout.PREFERRED_SIZE, 1474,
                                        Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(panelKanan, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(panelKiri, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Event Mouse Clicked pada tabel catatan harian (tblDiary)
     * Berfungsi Untuk ketika kita klik data di tabel, maka data yang di dalam tabel akan terisi ke text fieldnya masing masing
     */
    private void tblDiaryMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tblDiaryMouseClicked
        baris = tblDiary.getSelectedRow(); //membuat variabel "baris" untuk mengambil indeks baris yang sedang dipilih pada tabel
        tfTanggal.setText(tabel.getValueAt(baris, 0).toString()); //mengambil data dari tabel pada kolom indeks 0 (tanggal) ke dalam text field tanggal (tfTanggal)
        tfTema.setText(tabel.getValueAt(baris, 1).toString()); //mengambil data dari tabel pada kolom indeks 1 (tema) ke dalam text field tema (tfTema)
        taCatatanHarian.setText(tabel.getValueAt(baris, 2).toString()); //mengambil data dari tabel pada kolom indeks 2 (Isi) ke dalam text area Isi Catatan Harian (taCatatanHarian)

    }// GEN-LAST:event_tblDiaryMouseClicked

    /**
     * BUTTON TAMBAH
     * Berfungsi untuk menambahkan data dari text field ke dalam tabel
     */
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTambahActionPerformed
        String tanggal = tfTanggal.getText(); //mengambil teks dari text field tanggal (tfTanggal) dan menyimpan ke variabel tanggal
        String tema = tfTema.getText(); //mengambil teks dari text field tema (tfTema) dan menyimpan ke variabel tema
        String isi = taCatatanHarian.getText(); //mengambil teks dari text area isi catatan harian (taCatatanHarian) dan menyimpan ke variabel isi
        if (tanggal.isEmpty() || tema.isEmpty() || isi.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Harap isi Ketiga kolom", "Pesan Kesalahan", JOptionPane.ERROR_MESSAGE);
      
        }
        listCatatan.add(new Catatan(tanggal, tema, isi)); //menambahkan objek catatan yang memiliki atribut tanggal, tema, isi ke dalam arraylist listCatatan
        tabel.setRowCount(0); //mengatur jumlah baris pada model tabel menjadi 0
        for (int x = 0; x < listCatatan.size(); x++) {
            Object[] objek = { listCatatan.get(x).tanggal, listCatatan.get(x).tema, listCatatan.get(x).isi };
            tabel.addRow(objek);
        } ////memperbarui tampilan tabel setelah adanya perubahan dalam data catatan.
        tfTanggal.requestFocus(); //berfungsi untuk fokus ke komponen text field Tanggal (tfTanggal)
        tfTanggal.setText(""); //berfungsi untuk menghapus atau mengosongkan isi pada text field Tanggal (tfTanggal)
        tfTema.setText(""); //berfungsi untuk menghapus atau mengosongkan isi pada text field Tema (tfTema)
        taCatatanHarian.setText(""); //berfungsi untuk menghapus atau mengosongkan isi pada text area Isi Catatan Harian (taCatatanHarian)
    }// GEN-LAST:event_btnTambahActionPerformed

    /**
     * BUTTON EDIT
     * Berfungsi untuk mengedit data yang ada di dalam tabel, sesuai data kita klik pada tabel, lalu nanti akan muncul data tabel ke text fieldnya masing-masing dan dapat melakukan edit pada data tersebut, lalu klik button edit
     */
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditActionPerformed
        String editTanggal = tfTanggal.getText(); //mengambil teks dari text field tanggal (tfTanggal) dan menyimpan ke variabel editTanggal
        String editTema = tfTema.getText(); //mengambil teks dari text field tema (tfTema) dan menyimpan ke variabel editTema
        String editIsi = taCatatanHarian.getText(); //mengambil teks dari text area isi catatan harian (taCatatanHarian) dan menyimpan ke variabel editIsi
        listCatatan.get(baris).tanggal = editTanggal; //memperbarui nilai atribut tanggal 
        listCatatan.get(baris).tema = editTema; //memperbarui nilai atribut tema
        listCatatan.get(baris).isi = editIsi; //memperbarui nilai atribut isi
        tabel.setRowCount(0); //mengatur jumlah baris pada model tabel menjadi 0
        for (int x = 0; x < listCatatan.size(); x++) {
            Object[] objek = { listCatatan.get(x).tanggal, listCatatan.get(x).tema, listCatatan.get(x).isi };
            tabel.addRow(objek);
        }//perulangan yang berfungsi untuk menambahkan setiap data tanggal, tema, isi yang telah DIEDIT ke dalam tabel atau memperbarui tampilan tabel setelah adanya perubahan dalam data catatan.

    }// GEN-LAST:event_btnEditActionPerformed

    /**
     * BUTTON HAPUS
     * Berfungsi untuk menghapus data yang ada di dalam tabel, depat menghapus sesuai data kita klik pada tabel
     */
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHapusActionPerformed
        int ingfokan = JOptionPane.showConfirmDialog(this, "Anda yakin bang hapus data ini", "Hapus data", JOptionPane.YES_NO_CANCEL_OPTION); // Menampilkan pesan dengan opsi yes atau no
        if (ingfokan == 0) { //ketika pesan tersebut dipilih opsi yes
            tabel.removeRow(baris); //menghapus baris pada indeks 'baris' dari model tabel
            listCatatan.remove(baris); //menghapus objek class catatan pada indeks baris 
            tabel.setRowCount(0); //mengatur jumlah baris pada model tabel menjadi 0
            for (int x = 0; x < listCatatan.size(); x++) {
                Object[] objek = { listCatatan.get(x).tanggal, listCatatan.get(x).tema, listCatatan.get(x).isi };
                tabel.addRow(objek);
            } //memperbarui tampilan tabel setelah adanya perubahan dalam data catatan.
            tfTanggal.requestFocus(); //berfungsi untuk fokus ke komponen text field Tanggal (tfTanggal)
            tfTanggal.setText(""); //berfungsi untuk menghapus atau mengosongkan isi pada text field Tanggal (tfTanggal)
            tfTema.setText(""); //berfungsi untuk menghapus atau mengosongkan isi pada text field Tema (tfTema)
            taCatatanHarian.setText(""); //berfungsi untuk menghapus atau mengosongkan isi pada text area Isi Catatan Harian (taCatatanHarian)
        }

    }// GEN-LAST:event_btnHapusActionPerformed

    /**
     * BUTTON IMPOR
     */
    private void btnImporActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnImporActionPerformed
        String fileLokasi = "C:\\Users\\ROG\\Documents\\NetBeansProjects\\Project_UTS\\impor.txt"; //membuat variabel untuk menyimpan lokasi file yang akan diimpor.
        File file = new File(fileLokasi); //membuat objek File dengan menggunakan lokasi file

        try {//solusi agar ketika terjadi exception
            FileReader fr = new FileReader(file); //Membuat objek FileReader untuk membaca dari file
            BufferedReader br = new BufferedReader(fr); //Membuat objek BufferedReader untuk membaca dari file

            DefaultTableModel model = (DefaultTableModel) tblDiary.getModel(); //Mendapatkan model tabel dari objek tblDiary
            Object[] lines = br.lines().toArray(); //Membaca setiap baris dari file txt dan menyimpannya sebagai array objek

            for (int x = 0; x < lines.length; x++) {
                String[] row = lines[x].toString().split("\\|");
                model.addRow(row);
            } //Melakukan pembacaan melalui setiap baris dalam array dan menambahkannya sebagai baris baru ke dalam model tabel
            // Pembacaan kolom dapat terpotong atau terbagi ketika ada tanda "|" pada file txt. Ketika tidak ada tanda | maka data yang masuk ke tabel hanya pada kolom tanggal
        } catch (IOException ex) { //ketika terjadi exception, akan menampilkan Error exception pada terminal
            System.err.println("Error: " + ex.getMessage());
        }
    }// GEN-LAST:event_btnImporActionPerformed

    /**
     * BUTTON EKSPOR
     * Berfungsi untuk mengekspor data yang ada di tabel menjadi sebuah file txt
     */
    private void btnEksporActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEksporActionPerformed
        String fileLokasi = "C:\\Users\\ROG\\Documents\\NetBeansProjects\\Project_UTS\\ekspor.txt"; //membuat variabel untuk menyimpan lokasi file tujuan ekspor.
        File file = new File(fileLokasi); //membuat objek File dengan menggunakan lokasi file.

        try {//solusi agar ketika terjadi exception
            FileWriter pw = new FileWriter(file); //Membuat objek FileWriter untuk menulis ke file txt
            BufferedWriter bw = new BufferedWriter(pw); //Membuat objek BufferedWriter untuk menulis ke file txt

            for (int x = 0; x < tblDiary.getRowCount(); x++) {
                for (int y = 0; y < tblDiary.getColumnCount(); y++) {
                    bw.write(tblDiary.getValueAt(x, y).toString() + " | ");
                }
                bw.newLine();
            }// Melakukan pembacaan melalui seluruh sel dalam tabel dan menuliskan nilainya ke dalam file txt dengan memisahkannya menggunakan tanda "|" dan membuat baris baru setelah setiap baris tabel. Jadi setiap kolom yang sudah dibaca dan dituliskan, diantara kolom tersebut akan dibatasi dengan "|"
            JOptionPane.showMessageDialog(null, "Berhasil Disimpan dalam File"); //menampilkan pesan berhasil disimpan
            bw.close(); //Menutup BufferedWriter setelah selesai menulis ke file
            pw.close(); //Menutup FileWriter setelah selesai menulis ke file
        } catch (IOException ex) {//ketika terjadi exception, akan menampilkan Error exception pada terminal
            System.err.println("Error: " + ex.getMessage());
        }
    }// GEN-LAST:event_btnEksporActionPerformed

    /**
     * BUTTON EKSPOR
     */
    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLogOutActionPerformed
        LoginForm hlmLogin = new LoginForm(); //Membuat objek dari kelas LoginForm
        hlmLogin.setVisible(true); //Menampilkan form login ke layar
        dispose(); //Menutup form saat ini (CatatanHarian)
    }// GEN-LAST:event_btnLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatatanHarian.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatatanHarian.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatatanHarian.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatatanHarian.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatatanHarian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEkspor;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnImpor;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelKanan;
    private javax.swing.JPanel panelKiri;
    private javax.swing.JTextArea taCatatanHarian;
    private javax.swing.JTable tblDiary;
    private javax.swing.JTextField tfTanggal;
    private javax.swing.JTextField tfTema;
}